[config]
schemaVersion = "0.0.1"

[package]
namespace = "Thazzeus"
name = "PvPModes"
versionNumber = "0.1.0"
description = "Tools for a variety of PvP."
websiteUrl = "https://github.com/decaprime/CommunityCommands"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.668.5"
deca-VampireCommandFramework = "0.8.0"
deca-Bloodstone = "0.1.4"

[build]
icon = "./logo.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://v-rising.thunderstore.io"
communities = ["v-rising"]
categories = ["gloomrot-update", "mods", "server"]